import json
import os
import asyncio
import subprocess
import traceback
from telethon import TelegramClient
from telethon.sessions import StringSession
from playwright.async_api import async_playwright

API_ID = int(os.environ["TG_API_ID"])
API_HASH = os.environ["TG_API_HASH"]
SESSION_STRING = os.environ["TG_SESSION"]
CHANNEL_ID = int(os.environ["TG_CHANNEL_ID"])

FFMPEG_CMD = (
    "ffmpeg -y -f x11grab -video_size 1920x1080 -follow_mouse ignore -i :99.0 "
    "-f pulse -ac 2 -i default "
    "-c:v libx264 -preset ultrafast -crf 23 -pix_fmt yuv420p "
    "-c:a aac -b:a 128k "
)

client = TelegramClient(StringSession(SESSION_STRING), API_ID, API_HASH)

async def log_to_tg(message):
    """Helper function to broadcast real-time status logs directly into your channel"""
    print(message)
    try:
        await client.send_message(CHANNEL_ID, f"📝 **System Log:** {message}")
    except Exception as e:
        print(f"Failed to log to TG: {e}")

async def record_video(name, url, duration):
    output_file = f"{name}.mp4"
    await log_to_tg(f"🎬 Starting virtual recorder setup for: `{name}`")
    
    # Fire up background screen capture recorder
    record_proc = subprocess.Popen(
        f"{FFMPEG_CMD} \"{output_file}\"",
        shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    )
    
    async with async_playwright() as p:
        await log_to_tg("🌐 Launching secure browser environment...")
        browser = await p.chromium.launch(headless=False, args=["--start-maximized"])
        
        if os.path.exists("auth_state.json"):
            await log_to_tg("🔑 Injecting active authentication state cookies...")
            context = await browser.new_context(
                storage_state="auth_state.json",
                viewport={"width": 1920, "height": 1080},
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
            )
        else:
            await log_to_tg("⚠️ Warning: auth_state.json missing! Running unauthenticated...")
            context = await browser.new_context(viewport={"width": 1920, "height": 1080})
            
        page = await context.new_page()
        
        await log_to_tg(f"🚀 Loading targeted streaming endpoint: {url}")
        await page.goto(url)
        
        await asyncio.sleep(5)  # Let video player settle layout
        
        await log_to_tg(f"⏳ Now recording live... process will hold for **{duration} seconds**.")
        await asyncio.sleep(duration)
        
        await log_to_tg("🛑 Recording period completed. Closing cloud browser instance...")
        await browser.close()
        
    record_proc.terminate()
    record_proc.wait()
    return output_file

async def main():
    await client.start()
    
    with open("links.json", "r") as f:
        queue = json.load(f)
        
    await log_to_tg(f"📋 Pipeline loaded successfully. Total items found in batch: **{len(queue)}**")
    
    for idx, item in enumerate(queue, start=1):
        name = item["name"]
        url = item["url"]
        duration = item.get("duration", 60)
        
        await log_to_tg(f"🔄 **[Batch Element {idx}/{len(queue)}]** Processing `{name}`")
        
        try:
            file_path = await record_video(name, url, duration)
            
            if os.path.exists(file_path):
                file_size_mb = os.path.getsize(file_path) / (1024 * 1024)
                await log_to_tg(f"📦 Recording finished. Local payload size: `{file_size_mb:.2f} MB`. Sending raw file to channel...")
                
                if file_size_mb > 0:
                    await client.send_file(
                        CHANNEL_ID,
                        file_path,
                        caption=f"🎥 **Name:** {name}\n⏱️ **Duration:** {duration}s",
                        supports_streaming=True
                    )
                    await log_to_tg(f"✅ Success! `{name}` uploaded perfectly.")
                    os.remove(file_path)
                else:
                    await log_to_tg(f"❌ Aborted: Captured video file size is 0 bytes for `{name}`. Page might have failed to load.")
            else:
                await log_to_tg(f"❌ Aborted: The expected file path `{file_path}` was not generated by FFmpeg.")
                
        except Exception as e:
            err_stack = traceback.format_exc()
            await log_to_tg(f"💥 **Pipeline Error Caught on `{name}`:**\n```{str(e)}```")
            print(err_stack)
            
        # Anti-ban dynamic gap: Pause before switching context to the next item
        if idx < len(queue):
            await log_to_tg("🛡️ **Anti-Ban Interval:** Sleeping for 10 seconds to maintain a safe request profile...")
            await asyncio.sleep(10)
            
    await log_to_tg("🏁 All batch jobs processed. Pipeline execution shutdown complete.")

if __name__ == "__main__":
    asyncio.run(main())
